import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button } from "@mui/material";
import { getSession, signIn, signOut } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button onClick={() => signIn()}>signin</Button>
      <Button onClick={() => signOut()}>signout</Button>
    </>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  console.log("SESSION", session);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
};
