import Head from "next/head";
import { Inter } from "next/font/google";
import { getSession, signIn, signOut } from "next-auth/react";

import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Attensam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Box>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);
  console.log("SESSION", session);
  if (!session) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
  return {
    props: { session },
  };
};
